### ISSUE TITLE
Temporary files interfere with building assets

### ISSUE THREAD

**Issue by grandsbor** [openscope/openscope#1461]
Some text editors (e.g. vim) save temporary files in the same directory as the file being edited. So, if you edit an airline `xxx.json`, the assembler may found `.xxx.json.swp` in the assets/airlines dir, include it in the package and fail:

```
[13:37:30] SyntaxError: Unexpected token b in JSON at position 0
    at Object.parse (native)
    at fs.readdirSync.forEach (/home/grand/openscope/tools/tasks/jsonAssembler.js:40:31)
    at Array.forEach (native)
    at _buildResultList (/home/grand/openscope/tools/tasks/jsonAssembler.js:28:28)
    at _jsonAssembler (/home/grand/openscope/tools/tasks/jsonAssembler.js:91:20)
    at jsonAssembler (/home/grand/openscope/tools/tasks/jsonAssembler.js:109:9)
    at bound (domain.js:280:14)
    at runBound (domain.js:293:12)
    at asyncRunner (/home/grand/openscope/node_modules/async-done/index.js:55:18)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
[13:37:30] 'build' errored after 10 s
```

Suggestions: skip invisible files (i.e. those with names starting with `.`) or skip files not ending with `.json`

**Comment by erikquinn** [comment]
@n8rzz?

**Comment by n8rzz** [comment]
I always forget vim does that.  

The place to make this change would be [here](https://github.com/openscope/openscope/blob/develop/tools/options.js#L69).  We are using a pretty simple glob of `path.join(options.DIR.BUILD_ASSETS, 'airports/**/*')` to pick up files.  This should probably be updated to `path.join(options.DIR.BUILD_ASSETS, 'airports/**/*.json')` so the glob isn't so greedy.

**Comment by grandsbor** [comment]
Thx, such a patch does the trick:

```diff
-        if (fileSource.indexOf(outputFilename) !== -1) {
+        // also skip everything that doesn't end with '.json'
+        if (fileSource.indexOf(outputFilename) !== -1 || !fileSource.endsWith('.json')) {
```

**Comment by grandsbor** [comment]
Mind if I commit it this way? ^
