### ISSUE TITLE
Local installation fails due to 'git not installed'?

### ISSUE THREAD

**Issue by panther2** [openscope/openscope#382]
In the past (end of 2016) I have successfully locally installed ZLSA-ATC on a Win7-64 computer with just NodeJS installed. I had downloaded the develop.zip from the repository, uncompressed it to an app-directory and run `npm install` and `npm run build` . No problems.

Now trying the same with the latest openscope-develop.zip installation fails due to 

```
52532 verbose stack Error: not found: git
52532 verbose stack     at getNotFoundError (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:13:12)
52532 verbose stack     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:68:19)
52532 verbose stack     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:80:29)
52532 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:89:16
52532 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
52532 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
52532 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
52532 verbose stack     at FSReqWrap.oncomplete (fs.js:114:15)
52533 verbose cwd C:\Tools\OpDev
52534 error Windows_NT 6.1.7601
52535 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
52536 error node v7.9.0
52537 error npm  v4.2.0
52538 error code ENOGIT
52539 error not found: git
52540 error Failed using git.
52540 error This is most likely not a problem with npm itself.
52540 error Please check if you have git installed and in your PATH.
52541 verbose exit [ 1, true ]
```

So do I really need to install git now? And out of curiosity - what has changed that this is needed now?
Also in the file https://github.com/openscope/openscope/tree/develop/tools there is no requirement of an installed git mentioned, just NodeJS.

Not that I am not willing to install it - just wondering about the background of that change...

Thank you.

**Comment by n8rzz** [comment]
hmm, I guess I overlooked that requirement.  Yes, you will need git as it is what is used to download all the dependency packages.

**Comment by panther2** [comment]
Ah, ok, so there are new dependencies that had not been there before?

**Comment by n8rzz** [comment]
if you had installed the zlsa version from way back then, yes, lots of them 😉.  Most are used only for development, but yeah, there are a lot of tools that you'll need in order to get things running locally. luckily, 95% of them are installed with a simple `npm install`.
